name: Actualizador HiddenKernel

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  generar-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ejecutar actualizador
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python actualizador.py

      - name: Guardar cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add payloads.json

          if ! git diff --cached --quiet; then
            git commit -m "Actualizados payloads [skip ci]"
            git push
          else
            echo "No hay actualizaciones nuevas."
          fi
